spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaoshadesign?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false

  resources:
    static-locations: classpath:static/
    add-mappings: true
  mvc:
    static-path-pattern: /**
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


rabbitmq:
  topic: miaoSha
  routeKey: do_miaoSha

  rocketmq:
    topic: miaosha
    name-server: 127.0.0.1:9876
    producer:
       group: producer


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    Dao: debug




